name: test-molonari

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-pyheatmy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --timeout 300 pytest nbmake
        pip install --timeout 300 -e pyheatmy/

    - name: Test pyheatmy
      run: pytest pyheatmy/tests/ -v
      
    - name: Test Jupyter Notebooks
      run: |
        pytest --nbmake --nbmake-timeout=600 \
          pyheatmy/demoPyheatmy.ipynb \
          pyheatmy/demo_genData.ipynb
